### ISSUE TITLE
PrepareArm9ForTwl returned error c8804631!

### ISSUE THREAD

**Issue by radostin04** [TuxSH/universal-otherapp#1]
We saw this happen on two systems today in NH - both from normal regions. I'm mostly opening this up so that it can be looked into at some point - I'll do my best to provide any other required details

**Comment by ghost** [comment]
I got this error and i dont't know how to solve it

**Comment by coder43556644** [comment]
Got**

**Comment by ghost** [comment]
> Nous avons vu cela se produire sur deux systèmes aujourd'hui dans NH - tous deux des régions normales. J'ouvre principalement cela pour qu'il puisse être examiné à un moment donné - je ferai de mon mieux pour fournir tout autre détail requis

How to solve it

**Comment by GipepeXD** [comment]
hola alguien me ayuda a resolver este problema?

**Comment by radostin04** [comment]
This issue occurs when DS Internet Connections is missing from the system - it's unrelated to universal-otherapp. Anybody experiencing the issue will have to use an alternative method that does not require universal-otherapp.

**Comment by TuxSH** [comment]
https://github.com/TuxSH/kernelhaxcode_3ds/blob/8d00a64f5a9c23bff4a980fe0dd737e479a451a6/arm11/source/main.c#L12

You can alternatively try changing the TID there^
