### ISSUE TITLE
Got white and red screen error. System version: 9.3.0-16T (TWN)

### ISSUE THREAD

**Issue by zhangfangte** [TuxSH/universal-otherapp#4]
My Nintendo 3DS is Traditional Chinese version, it shows [**Ver. 9.3.0-16T**] in System Config. None of hacks had been done on this console. (I can promise this because I bought it as a new console in 2013 and never lend it to other people)
I tried Soundhax, and got white and red screen error immediately for everytimes. Then I changed  SD card and tried more times, and got the same results. I guess universal-otherapp may not compete with this system version now...
(By the way, since [Homebrew Launcher (Soundhax)] and [Seedminer] do not support Chinese version , I have no idea how to hack my 3DS now...)

**Comment by lifehackerhansol** [comment]
Please join [Nintendo Homebrew](https://discord.gg/C29hYvh) to discuss about it. It should be possible to hack this device but not publicized on a guide.
